### ISSUE TITLE
Add modal window component

### ISSUE THREAD

**Issue by apust** [cft-group/elephas#122]
In most cases it is not recommended to use modal windows with Elephas. But sometimes it is the most reasonable option.

Styles suggested by @Amil-Gaoul:

```SCSS
._e_dialog {
    padding: var(--S32);
    border-radius: 4px;
    box-shadow: 0 1px 4px rgba(0, 0, 0, 0.04), 0 8px 32px rgba(0, 0, 0, 0.24);
    background-color: var(--N0);
}
/* e-dialog-title */
._e_dialog__heading {
    display: flex;
    justify-content: space-between;
    align-items: center;
}
._e_dialog__title {
    color: var(--N800);
    font: var(--H1);
}
._e_dialog__icon {
    width: var(--S24);
    height: var(--S24);
    cursor: pointer;
    fill: var(--N200);
    &:hover {
        fill: var(--N600);
    }
}
/* e-dialog-content */
._e_dialog__content {
    color: var(--N800);
    font: var(--Subhead);
    margin-top: var(--S24);
}
/* e-dialog-actions */
._e_dialog__actions {
    display: flex;
    align-items: center;
    margin-top: var(--S24);
    & > *:not(:last-child) {
        margin-right: var(--S24);
    }
}
```
