### ISSUE TITLE
Passive Breadcrumbs item changes color on mouse click 

### ISSUE THREAD

**Issue by apust** [cft-group/elephas#130]
`:active` selector is more specific than `._e_breadcrumbs__item_passive` modifier class. Therefore, we get this: 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/2337671/107639747-e5743780-6ca3-11eb-85b2-e710395955c4.png">

One way to solve this would be to change `:active` css line to this:

```CSS
._e_breadcrumbs__item:not(._e_breadcrumbs__item_passive):active { ... }
```

Thanks to @qworin for reporting this.

**Comment by qworin** [comment]
This issue appears in :focus state as well. This is more readable code to resolve both issues:
```scss
._e_breadcrumbs__item_passive {
  &:active, &:focus {
    color: var(--N600);
  }
}
```
