### ISSUE TITLE
Chrome user agent stylesheet messes up with Select appearance

### ISSUE THREAD

**Issue by apust** [cft-group/elephas#87]
`<Select appearance="readonly" disabled />` has less legible text because of Chrome's CSS:

```CSS
select:disabled {
    opacity: 0.7;
}
```
